---
- hosts: pxc
  tasks:
    - name: ping server
      ping:
    - shell: 'echo $HOSTNAME'
      register: name
    - shell: 'hostname | grep -o ..$'
      register: uuname
    - name: copy wsrep.cnf
      copy: 
        src: wsrep.cnf
        dest: /etc/percona-xtradb-cluster.conf.d/
    - name: copy mysql.conf
      copy: 
        src: mysqld.cnf
        dest: /etc/percona-xtradb-cluster.conf.d/
    - name: change mysql.cnf
      replace: 
        path: /etc/percona-xtradb-cluster.conf.d/mysqld.cnf
        regexp: "1"
        replace: "{{uuname.stdout}}"
    - name: change wsrep.conf
      replace: 
        path: /etc/percona-xtradb-cluster.conf.d/wsrep.cnf
        regexp: pxc-cluster-node-1
        replace: "{{name.stdout}}"
    - name: change ip_wsrep.conf
      replace: 
        path: /etc/percona-xtradb-cluster.conf.d/wsrep.cnf
        regexp: "192.168.70.63"
        replace: "{{ansible_default_ipv4.address}}"
        
    - name: restart server
      service: 
        name: "{{servername}}" 
        enabled: yes
        state: restarted 
     
